[package]
name = "todo-rust-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "todo"          
path = "src/main.rs" 

[dependencies]
clap = "4.5.43"
colored = "3.0.0"
directories = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
